### ISSUE TITLE
Link do curso não disponível.

### ISSUE THREAD

**Issue by doougui** [robertoachar/Aprenda-Markdown#1]
Olá Roberto. Tentando acessar o curso pelo [link disponibilizado no README](https://markdown.showmethecode.com.br/) do repositório eu notei que a página não está mais disponível.

**Comment by robertoachar** [comment]
@doougui

Eu preciso atualizar o repo.

Agradeço de coração pela issue.

Migrei meu curso para a Udemy.

Esse é o link: https://www.udemy.com/course/aprenda-markdown/

Feedback são muito bem-vindos. Bons estudos, man.

**Comment by doougui** [comment]
Sem problemas, vou acessar pela Udemy então :D

**Comment by robertoachar** [comment]
@doougui Conseguiu acessar?

**Comment by doougui** [comment]
Sim, consegui acessar pela Udemy
